# Generated by Django 3.2.5 on 2021-08-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HellowWorld',
            new_name='HelloWorld',
        ),
    ]
