# Generated by Django 3.2.6 on 2021-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_hellowworld_helloworld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
